### ISSUE TITLE
LaTeX for package development and building needed?

### ISSUE THREAD

**Issue by seandavi** [Bioconductor/bioconductor_full#10]

**Comment by nturaga** [comment]
Yes, you'd need to install `tinyTex`. This is a design decision we took to reduce the size of the image by about 200-300MB.

https://yihui.name/tinytex/

```
install.packages('tinytex')
tinytex::install_tinytex()
```

A good solution is, make another dockerfile which inherits from bioconductor_full, and runs the code above. This would **save** all the settings needed for tinytex to work as expected each time the image is restarted. 

Does this help @seandavi ?

**Comment by seandavi** [comment]
Thanks, @nturaga. That does the trick.

**Comment by lwaldron** [comment]
For posterity, tinytex requires a couple tricks for a system-wide installation. Also, I found it felt like whack-a-mole adding the extra packages needed to compile vignettes, and ended up just adding a couple GB with texinfo + texlive + texlive-fonts-extra to not have to worry about it anymore. Code for both approaches (with tinytex commented out) at https://github.com/waldronlab/bioconductor/blob/master/Dockerfile.

**Comment by seandavi** [comment]
Does this work for you, @lwaldron:

https://github.com/Bioconductor/bioconductor_full#frequently-asked-questions-faq

If not, perhaps we should update the FAQ with more detail and fine-grained documentation about what works and what doesn't?
