### ISSUE TITLE
Running `release` and `devel` simultaneously

### ISSUE THREAD

**Issue by lwaldron** [Bioconductor/bioconductor_full#12]
Using the current instructions, you can't run release and devel RStudio servers at the same time on the same computer. Could you provide documentation for running both simultaneously, accessible from the web browser on different ports or IP addresses?

**Comment by lwaldron** [comment]
I find that the solution documented in https://github.com/Bioconductor/bioconductor_full/commit/f773a1c3e2b4b68f3b971b4d13f96a0a6d80ea4e doesn't actually work for me - I can browse to the two instances, but as soon as I authenticate in the second rstudio instance, I get logged out of the first.  Running on OSX.

**Comment by mtmorgan** [comment]
hmm, the scenario 'works for me' also on macOS. This sounds like the behave of R Studio running two sessions from the same docker container? E.g., going to localhost:8787 for both login attempts?

**Comment by lwaldron** [comment]
As two tabs in the same browser? I can't do it in the same browser, but can in different browsers, following the advice at https://github.com/rocker-org/rocker/issues/104.

**Comment by LiNk-NY** [comment]
I can confirm that it works for me when using two _different_ browsers (chrome & chromium). 
I go to `localhost:8787` on one browser and `localhost:8788` on the other.
It does not work if I use the same browser on multiple tabs (as stated in the issue: rocker-org/rocker#104)

**Comment by lwaldron** [comment]
It also works for me if I use two Chrome "private" browsers, or one normal and one private.

**Comment by mtmorgan** [comment]
well two tabs in the same (chrome) browser each connecting to a different image works for me (chrome on macOS)... the issue in rocker is quite old, though obviously something is wrong...
