### ISSUE TITLE
Will there be a RELEASE_3_10 tag soon?

### ISSUE THREAD

**Issue by jorainer** [Bioconductor/bioconductor_full#13]
First of all thanks for the great resource! These docker images simplified the way I'm dealing with several R/Bioconductor releases considerably.

I was however wondering if you plan to create a *RELEASE_3_10* tag soon? I guess the *devel* tag is the next Bioconductor version (3.11) and I'm using also the *RELEASE_3_9* tag - but don't have a docker/installation for the current 3.10 release.

**Comment by lshep** [comment]
The release docker that this image was based on was generated yesterday so I imagine it being up in the next few days. 
We are debugging the devel docker and I would imagine also have that out early next week.

**Comment by nturaga** [comment]
It's on it's way. #15

**Comment by nturaga** [comment]
The RELEASE_3_10 branch is now available @jorainer

**Comment by lwaldron** [comment]
Thanks Nitesh.
