### ISSUE TITLE
Consider adding GPL2 license text and header

### ISSUE THREAD

**Issue by heuermh** [Bioconductor/bioconductor_full#3]
Hello,

Though I heard this repository is licensed GPL2, I couldn't find any licensing information.

Per [How to use GNU licenses for your own software](https://www.gnu.org/licenses/gpl-howto.html), GPL2 projects should include a copy of the license itself (in a file called COPYING, by convention) and a license notice in the header of every source file.

Thanks in advance!

**Comment by mtmorgan** [comment]
Can you clarify what you mean? Is there a statement of license in this repository?

**Comment by heuermh** [comment]
> Is there a statement of license in this repository?

Not that I can find.  :)

I'm on the program committee for the [BOSC conference](https://www.open-bio.org/wiki/BOSC) following up on an abstract submission, which pointed to this repository and said it was licensed GPL-2.

**Comment by nturaga** [comment]
@heuermh Pull request #4 which is now merged addresses this. Thanks for filing an issue.

**Comment by heuermh** [comment]
Thank you, @nturaga
