### ISSUE TITLE
What would it take to install the build system into bioconductor_full?

### ISSUE THREAD

**Issue by seandavi** [Bioconductor/bioconductor_full#9]
If this were a possibility, it would render the build system portable and reusable.

**Comment by mtmorgan** [comment]
the 'build system' includes native Windows and MacOS so having a docker image doesn't make the build system portable... The build system also consists of components unrelated to building R packages per se, e.g., coordinating via rsync across different builders. And the build system invokes R in a series of logical steps and with particular flags (see at the top of each section of the build report for each install / build / check stage) that may not make sense when testing packages.

It doesn't seem impossible to imagine that the package build process could be based on a docker image.... probably there is a different Docker layer that implements reproducibility on top of the purpose that bioconductor_full aims for.

**Comment by hpages** [comment]
Also the build system is a constantly moving target: we need to go on the build machines on a regular basis to make manual changes in order to keep up with new R versions and new system requirements, and for routine maintenance.

**Comment by seandavi** [comment]
> the 'build system' includes native Windows and MacOS so having a docker image doesn't make the build system portable... The build system also consists of components unrelated to building R packages per se, e.g., coordinating via rsync across different builders. And the build system invokes R in a series of logical steps and with particular flags (see at the top of each section of the build report for each install / build / check stage) that may not make sense when testing packages.

Totally get that MacOS and Windows are a different story.  


> It doesn't seem impossible to imagine that the package build process could be based on a docker image.... probably there is a different Docker layer that implements reproducibility on top of the purpose that bioconductor_full aims for.

I don't know of one--hence the use of .tgz of installed packages for the bioconductor workshop materials.

**Comment by seandavi** [comment]
> Also the build system is a constantly moving target: we need to go on the build machines on a regular basis to make manual changes in order to keep up with new R versions and new system requirements, and for routine maintenance.

Good to know what the current process is and that it is very hands-on.

**Comment by mtmorgan** [comment]
When I said 'probably there is a different Docker layer...' I meant a docker image the intended to replicate the build system would probably build on top of bioconductor_full, rather than be implemented by bioconductor_full
